GET http://localhost:5084/Pokedex

###
GET http://localhost:5084/Pokedex/2

###
POST http://localhost:5084/Pokedex
Content-Type:application/json

{
          "name":"Pidgeotto",
          "height":"3' 07",
          "weight": "66.1 lbs",
          "categoryId":4,
          "abilities":"Keen Eye, Tangled Feet"
}

###
PUT http://localhost:5084/Pokedex/4
Content-Type:application/json

{
        "name":"Pidgeotto 2nd",
        "height":"3' 10",
        "weight": "66.1 lbs",
        "categoryId":4,
        "abilities":"Keen Eye, Tangled Feet"
}

###
DELETE http://localhost:5084/Pokedex/5


###
GET http://localhost:5084/Category